version: 2

sources:
  - name: raw_orders
    description: "Sources for orders model"
    database: raw_dbt
    schema: shop
    tables:
      - name: orders
        description: "Raw table containing all transactions data"

models:
  - name: stg_customers
    description: "Cleaned data for customers data from raw source"
    columns:
      - name: customer_name
        description: "Customers Name"
        tests:
          - not_null
      - name: email
        description: "Customers Email Address"
        tests:
          - not_null
      - name: phone
        description: "Customers Phone Number"
        tests:
          - not_null
      - name: updated_at
        description: "Customers latest changes date"
        tests:
          - not_null
  - name: stg_orders
    description: "Cleaned and standardized order-level data from the raw source. Each row represents an individual product item in a customer's order."
    columns:
      - name: order_id
        description: "Identifier for each order transaction."
        tests:
          - not_null
      - name: order_date
        description: "Timestamp indicating when the order was placed."
        tests:
          - not_null
      - name: customer_id
        description: "Unique identifier of the customer who placed the order."
        tests:
          - not_null
      - name: product_name
        description: "Name of the product purchased in the order."
        tests:
          - not_null
      - name: quantity
        description: "Number of units purchased for the given product in the order."
        tests:
          - not_null
          - expect_positive
      - name: price
        description: "Unit price of the product at the time of purchase."
        tests:
          - not_null
          - expect_positive
      - name: net
        description: "Total amount before shipping, calculated as (quantity × price)."
        tests:
          - not_null
          - expect_positive
      - name: payment_method
        description: "Method used by the customer to pay for the order."
        tests:
          - not_null
          - accepted_values:
              values:
                - 'Credit Card'
                - 'PayPal'
                - 'Bank Transfer'
                - 'Cash'
      - name: shipping_address
        description: "Destination address where the order is to be delivered."
        tests:
          - not_null
      - name: shipping_cost
        description: "Cost incurred to ship the order to the customer."
        tests:
          - not_null
          - expect_at_least_zero
      - name: shipping_status
        description: "Current shipping status of the order"
        tests:
          - not_null
      - name: discount
        description: "Discount amount applied to the order item."
        tests:
          - expect_at_least_zero
      - name: updated_at
        description: "Timestamp indicating when the record was last updated in the source system."
        tests:
          - not_null
  - name: stg_products
    description: "Cleaned data for each product from the raw source."
    columns:
      - name: product_name
        description: "Name of each product"
        tests:
          - not_null
          - unique
      - name: category
        description: "Category of each product"
        tests:
          - not_null